GET http://localhost:3000/api/notificaciones


### POST a notificacion
# @name createNotificacion1
POST http://localhost:3000/api/notificaciones
Content-Type: application/json

{
    "promocion": "Descuento Black Friday",
    "porcentaje_promocion": 25,
    "dias_disponibles": [1, 2, 3, 4, 5],
    "tipo_promocion": "porcentaje",
    "max_interes": 15
}

### ID
@id = {{createNotificacion1.response.body.data.id}}

### GET one notificacion
http://localhost:3000/api/notificaciones/{{id}}

### PUT a notificacion
PUT http://localhost:3000/api/notificaciones/{{id}}
Content-Type: application/json

{
    "promocion": "Cyber Monday Super Oferta",
    "porcentaje_promocion": 30,
    "dias_disponibles": [1, 2, 3, 4, 5, 6, 7],
    "tipo_promocion": "descuento",
    "max_interes": 20
}

### POST otra notificacion
POST http://localhost:3000/api/notificaciones
Content-Type: application/json

{
    "promocion": "Descuento Fin de Semana",
    "porcentaje_promocion": 15,
    "dias_disponibles": [6, 7],
    "tipo_promocion": "reintegro",
    "max_interes": 10
}

### POST a notificacion para eliminar
# @name createNotificacionToDelete
POST http://localhost:3000/api/notificaciones
Content-Type: application/json

{
    "promocion": "Promo Temporal",
    "porcentaje_promocion": 5,
    "dias_disponibles": [1, 3, 5],
    "tipo_promocion": "cashback",
    "max_interes": 8
}

### DELETE a notificacion
@idToDelete = {{createNotificacionToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/notificaciones/{{idToDelete}}

### PATCH a notificacion
PATCH http://localhost:3000/api/notificaciones/{{id}}
Content-Type: application/json

{
    "porcentaje_promocion": 35,
    "max_interes": 25
}

### DELETE a notificacion
DELETE http://localhost:3000/api/notificaciones/{{idToDelete}}
