### Obtener todos los beneficios
GET http://localhost:3000/api/beneficios

###

### Obtener un beneficio por ID
GET http://localhost:3000/api/beneficios/27008bf3-517e-4ef5-9d24-c4a95f010eda

###

### Crear un nuevo beneficio
POST http://localhost:3000/api/beneficios
Content-Type: application/json

{
    "name": "Descuento Estudiantil",
    "porcentaje": 15,
    "descripcion": "Descuento para estudiantes",
    "fechaInicio": "2024-01-01",
    "fechaFin": "2024-12-31",
    "mentodoPago": ["tarjeta"],
    "tipoDescuento": "estudiante"
}

###

### Actualizar un beneficio existente
PUT http://localhost:3000/api/beneficios/68c46436a1a65b4dce9ba3e1
Content-Type: application/json

{
    "name": "Descuento Jubilado",
    "porcentaje": 20,
    "descripcion": "Descuento para jubilados",
    "fechaInicio": "2024-01-01",
    "fechaFin": "2024-12-31",
    "mentodoPago": ["tarjeta"],
    "tipoDescuento": "jubilado"
}

###

### Eliminar un beneficio
DELETE http://localhost:3000/api/beneficios/68c46436a1a65b4dce9ba3e1