GET http://localhost:3000/api/rubros


### POST a rubro
# @name createRubro1
POST http://localhost:3000/api/rubros
Content-Type: application/json

{
    "nombre": "Gastronomía",
    "descripcion": "Restaurantes, bares y lugares de comida"
}

### ID
@id = {{createRubro1.response.body.data.id}}

### GET one rubro
http://localhost:3000/api/rubros/{{id}}

### PUT a rubro
PUT http://localhost:3000/api/rubros/{{id}}
Content-Type: application/json

{
    "nombre": "Entretenimiento",
    "descripcion": "Cines, teatros, eventos y espectáculos"
}

## DELETE a rubro

DELETE http://localhost:3000/api/rubros/{{id}}

### POST otro rubro
POST http://localhost:3000/api/rubros
Content-Type: application/json

{
    "nombre": "Salud",
    "descripcion": "Farmacias, clínicas y servicios médicos"
}

