GET http://localhost:3000/api/personas


### POST a character
# @name createVader
POST http://localhost:3000/api/personas
Content-Type: application/json

{
    "name": "Tralalero tralala",
    "apellido": "kuka",
    "email": "laureanolanselotto@gmail.com",
    "tel": 2477309919,
    "dni": 12345678,
    "direccion": "Calle Falsa 123",
    "wallets": ["68e18d8f646f6244dd9f0d21", "68e18dfd646f6244dd9f0d22"]
}

### ID
@id = {{createVader.response.body.data.id}}

### DELETE url HTTP/1.1
DELETE http://localhost:3000/api/personas/68e18414c4ae0b9e35f732e9

### GET one character
http://localhost:3000/api/personas/{{id}}

### PUT a character
PUT http://localhost:3000/api/personas/{{id}}
Content-Type: application/json

{
    "name": "lirili larila",
    "apellido": "gay",
    "email": "tralalerito@gmail.com",
    "tel": 2477309919,
    "direccion": "Calle Falsa 123",
    "wallets": ["673f123456789012345678a1"]
}

### POST a character
POST http://localhost:3000/api/personas
Content-Type: application/json

{
   "name": "Tralalero tralala",
    "apellido": "kuka",
    "email": "laureanolanselotto@gmail.com",
    "tel": 2477309919,
    "dni": 12345678,
    "wallets": ["673f123456789012345678a3", "673f123456789012345678a4"]
}
}

### POST a character
# @name createCharacterToDelete
POST http://localhost:3000/api/personas
Content-Type: application/json

{
    "name": "tun tun sajur",
    "apellido": "no",
    "personaClass": "68d0b3e6fc9576467f753938",
    "items": [" 68cf79ce11d051e27c6c74ca"," 68cf79f111d051e27c6c74cb"],
    "email": "laureanolanselotto@gmail.com",
    "tel": 2477309919,
    "dni": 12345678
}
### DELETE a character
@idToDelete = {{createCharacterToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/personas/{{idToDelete}}

### PATCH a character
PATCH http://localhost:3000/api/personas/{{idToDelete}}
Content-Type: application/json

{
  "dni": 6,
  "wallets": ["673f123456789012345678a5"]
}

### DELETE a character
DELETE http://localhost:3000/api/personas/{{idToDelete}}
