### obtener todos los personajes

GET http://localhost:3000/api/personas

### obtener todos una persona en particular

GET http://localhost:3000/api/personas/6880239a570e1552a5d54a71
### crear una persona
POST http://localhost:3000/api/personas
Content-Type: application/json

{
    "name": "Juan",
    "apellido": "Pérez",
    "email": "lasda@gmail.com",
    "tel":231241,
    "dni": 12345678,
    "id": " "
}
### modificar  una persona (PUT y PATCH)
PUT  http://localhost:3000/api/personas/687acebb7d57801a84717e1b
Content-Type: application/json

{
    "name": "queso",
    "apellido": "hola",
    "email": "puto@gmail.com",
    "tel": 325425,
    "dni": 123456723558,
    "id": " "
}

### modifica una persona (PATCH - recurso parcial es decir partes de la persona) 
PATCH  http://localhost:3000/api/personas/12345678-1234-1234-1234-123456789012   
Content-Type: application/json

{
    "name": "sexo",
    "apellido": "gay",
    "email": "nomeleas@gmail.com"
}
### eliminar una persona
DELETE http://localhost:3000/api/personas/687ad358c4f7a5c4fbe39650