GET http://localhost:3000/api/personas

// ciudad = 68e3391749cdc20f677c8ca3
### POST a character
# @name createVader
POST http://localhost:3000/api/personas
Content-Type: application/json

{
    "name": "Tralalero tralala",
    "apellido": "kuka",
    "email": "laureanolanselotto@gmail.com",
    "tel": "2477309919",
    "dni": "12345678",
    "direccion": "Calle narnia 123",
    "wallets": [ "68e48baded6d35261b611518","68e5b6e003cec7b6df2b5e1c"],
    "ciudadId": "68e3391749cdc20f677c8ca3",
    "localidadId": "68e5b58603cec7b6df2b5e19"
}

### ID
@id = {{createVader.response.body.data.id}}

### DELETE url HTTP/1.1
DELETE http://localhost:3000/api/personas/{{id}}

### GET one character
GET http://localhost:3000/api/personas/{{id}}

### PUT a character
PUT http://localhost:3000/api/personas/{{id}}
Content-Type: application/json

{
    "nombres": "lirili larila",
    "apellidos": "gay",
    "email": "tralalerito@gmail.com",
    "telefono": "2477309919",
    "ubicacion": "Calle Falsa 123",
    "wallets": ["68e18d8f646f6244dd9f0d21"]
}

### POST a character
POST http://localhost:3000/api/personas
Content-Type: application/json

{
   "nombres": "Tralalero tralala",
    "apellidos": "kuka",
    "email": "laureanolanselotto@gmail.com",
    "telefono": "2477309919",
    "ubicacion": "Calle narnia 123",
    "wallets": ["68e18d8f646f6244dd9f0d21", "68e18e16646f6244dd9f0d23"]
}


### POST a character
# @name createCharacterToDelete
POST http://localhost:3000/api/personas
Content-Type: application/json

{
    "nombres": "tun tun sajur",
    "apellidos": "no",
    "email": "laureanolanselotto@gmail.com",
    "telefono": "2477309919",
    "ubicacion": "Calle prueba 123",
    "wallets": ["68e18d8f646f6244dd9f0d21"]
}
### DELETE a character
@idToDelete = {{createCharacterToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/personas/{{idToDelete}}

### PATCH a character
PATCH http://localhost:3000/api/personas/{{idToDelete}}
Content-Type: application/json

{
  "telefono": "2477309999",
  "wallets": ["68e18e16646f6244dd9f0d23"]
}

### DELETE a character
DELETE http://localhost:3000/api/personas/{{idToDelete}}
