GET http://localhost:3000/api/localidades


### POST a localidad
# @name createLocalidad1
POST http://localhost:3000/api/localidades
Content-Type: application/json

{
    "coordenadas": "-34.6118,-58.3960",
    "calles": "Av. Corrientes y Callao",
    "numero_calle": 1234
}

### ID
@id = {{createLocalidad1.response.body.data.id}}

### GET one localidad
http://localhost:3000/api/localidades/{{id}}

### PUT a localidad
PUT http://localhost:3000/api/localidades/{{id}}
Content-Type: application/json

{
    "coordenadas": "-34.6037,-58.3816",
    "calles": "Av. 9 de Julio y Rivadavia",
    "numero_calle": 5678
}

### POST otra localidad
POST http://localhost:3000/api/localidades
Content-Type: application/json

{
    "coordenadas": "-34.5875,-58.3974",
    "calles": "Av. Santa Fe y Pueyrredón",
    "numero_calle": 9012
}

### POST a localidad
# @name createCharacterToDelete
POST http://localhost:3000/api/localidades
Content-Type: application/json

{
    "name": "tun tun sajur",
    "apellido": "no",
    "personaClass": "68d0b3e6fc9576467f753938",
    "items": [" 68cf79ce11d051e27c6c74ca"," 68cf79f111d051e27c6c74cb"],
    "email": "laureanolanselotto@gmail.com",
    "tel": 2477309919,
    "dni": 12345678
}
### DELETE a localidad
@idToDelete = {{createCharacterToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/localidades/{{idToDelete}}

### PATCH a localidad
PATCH http://localhost:3000/api/localidades/{{idToDelete}}
Content-Type: application/json

{
  "dni": 6,
  "personaClass":"6531d4aedc98243fffe841e5",
  "items": ["6531d4f9dc98243fffe841e7"]
}

### DELETE a localidad
DELETE http://localhost:3000/api/localidades/{{idToDelete}}
