GET http://localhost:3000/api/localidad


### POST a localidad
# @name createVader
POST http://localhost:3000/api/localidad
Content-Type: application/json

{
    "name": "Tralalero tralala",
    "apellido": "kuka",
    "personaClass": "68d0b3e6fc9576467f753938",
    "items": [" 68cf79ce11d051e27c6c74ca"," 68cf79f111d051e27c6c74cb"],
    "email": "laureanolanselotto@gmail.com",
    "tel": 2477309919,
    "dni": 12345678
}

### ID
@id = {{createVader.response.body.data.id}}

### GET one localidad
http://localhost:3000/api/localidad/{{id}}

### PUT a localidad
PUT http://localhost:3000/api/localidad/{{id}}
Content-Type: application/json

{
"name": "lirili larila",
    "apellido": "gay",
    "items": [" 68cf79ce11d051e27c6c74ca"],
    "email": "tralalerito@gmail.com",
    "tel": 2477309919,
    "dni": 12345678
}

### POST a localidad
POST http://localhost:3000/api/localidad
Content-Type: application/json

{
   "name": "Tralalero tralala",
    "apellido": "kuka",
    "personaClass": "68d0b3e6fc9576467f753938",
    "items": [" 68cf79ce11d051e27c6c74ca"," 68cf79f111d051e27c6c74cb"],
    "email": "laureanolanselotto@gmail.com",
    "tel": 2477309919,
    "dni": 12345678
}

### POST a localidad
# @name createCharacterToDelete
POST http://localhost:3000/api/localidad
Content-Type: application/json

{
    "name": "tun tun sajur",
    "apellido": "no",
    "personaClass": "68d0b3e6fc9576467f753938",
    "items": [" 68cf79ce11d051e27c6c74ca"," 68cf79f111d051e27c6c74cb"],
    "email": "laureanolanselotto@gmail.com",
    "tel": 2477309919,
    "dni": 12345678
}
### DELETE a localidad
@idToDelete = {{createCharacterToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/localidad/{{idToDelete}}

### PATCH a localidad
PATCH http://localhost:3000/api/localidad/{{idToDelete}}
Content-Type: application/json

{
  "dni": 6,
  "personaClass":"6531d4aedc98243fffe841e5",
  "items": ["6531d4f9dc98243fffe841e7"]
}

### DELETE a localidad
DELETE http://localhost:3000/api/localidad/{{idToDelete}}
